development:
  adapter: postgresql
  encoding: unicode
  database: appname_development
  host: localhost
  pool: 5
  timeout: 5000
  username: appuser 
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: appname_test
  host: localhost
  pool: 5
  timeout: 5000
  username: appuser
  password: password
